dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: EbOnWR3yQVJg27pP0+kHr9NEg/aUZxtLXyuWXfxlWRVTZRGrWrFd4dQ/zqTbrndspHGZTZpcaqnCaLUrkmuWYiWWJKMPAordZ5dP0L52ugWJ9hbpG/74ooC3yvxUlIIvZPyjx/FWzH4RxM1M2hpbnqC6VPi6g1XNOXNGKVUTyZJx6EGQ8GEZBx17DSRBGSD81VlSo8wQWASkdl1VR5x7qtjlTG8Qr1tcn48CJK1RalPns6eoBdEfUCod85yxkYIQShMz+/XYeF+FRcu1lFKGA8Jx0amTlCjM8yRtw5Jg8TTga2MDek38sZGfcNw9hIfrO6cEOR4P69yO+hD3f3wvVxjq+HWw+jyA6l7vEgr1dAByd9lELssqB4EOC0zVyY1pLlwdpG8KjTjbZhErVQKzvfASZavKr/bPcdA2y1gFvQJaF8KLRl9dc+2y6h8SRjQkEsrJGKwc1YIX621qcwDOqfI80WuNF5uRQMtS0bKF0omem+ZNDxLFBw6TzuifGB6b8Fuh5aVptEFJZofJ8E+y0O2WH3//8tDG+0LEHqcADGVP2FwpOckBEOA6q38eAIApR4iGKTITXXwlpKZiD8KSYdy/ugy3ttPKISsqdHrkfq8h1a4JFjsd+j/062Ybrq1Bq0QXI5jyWADSmhluHBp68cEkuOS/LGezeHjloQv9f4w=
  file: Gerbers/PIN-100_gerbers.zip
  on:
    repo: w4xzr/PIN-100
  skip_cleanup: 'true'
